# **2. Pandas**
### Limpeza, verificações e transformações da planilha Pessoas utilizando Pandas

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
from google.cloud import storage

##### Lê arquivo concatenado na GCS

In [2]:
df=pd.read_json('gs://projetofinalsc/dadosbrutos/pessoas/acidentes_pessoas.json',lines=True, orient='records')

In [3]:
df

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,classificacao_acidente,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,id_veiculo,tipo_veiculo,marca,ano_fabricacao_veiculo,tipo_envolvido,estado_fisico,idade,sexo,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop
0,8,1.0,2017-01-01,domingo,00:00:00,PR,376.0,112,PARANAVAI,Fenômenos da Natureza,Queda de ocupante de veículo,Com Vítimas Feridas,Plena Noite,Crescente,Chuva,Simples,Reta,Não,5.0,Motocicleta,HONDA/CG 150 TITAN ESD,2005.0,Condutor,Lesões Graves,19.0,Masculino,0,0,1,0,"-23,09880731","-52,38789369",SR-PR,DEL7/7,UOP05/PR
1,9,955.0,2017-01-01,domingo,00:01:00,SC,101.0,234,PALHOCA,Falta de Atenção à Condução,Colisão com objeto estático,Sem Vítimas,Plena Noite,Crescente,Chuva,Dupla,Curva,Não,7.0,Automóvel,FIAT/PALIO WEEKEND EX,2003.0,Condutor,Ileso,35.0,Masculino,1,0,0,0,"-27,8101","-48,6357",SR-SC,DEL8/1,UOP02/SC
2,11,3.0,2017-01-01,domingo,00:00:00,PR,153.0,"56,9",SANTO ANTONIO DA PLATINA,Animais na Pista,Capotamento,Com Vítimas Feridas,Plena Noite,Decrescente,Garoa/Chuvisco,Simples,Reta,Não,6.0,Automóvel,VW/NOVO GOL 1.0,2013.0,Passageiro,Lesões Leves,27.0,Masculino,0,1,0,0,"-23,36951985","309,93513107",SR-PR,DEL7/7,UOP07/PR
3,11,2.0,2017-01-01,domingo,00:00:00,PR,153.0,"56,9",SANTO ANTONIO DA PLATINA,Animais na Pista,Capotamento,Com Vítimas Feridas,Plena Noite,Decrescente,Garoa/Chuvisco,Simples,Reta,Não,6.0,Automóvel,VW/NOVO GOL 1.0,2013.0,Condutor,Lesões Leves,27.0,Feminino,0,1,0,0,"-23,36951985","309,93513107",SR-PR,DEL7/7,UOP07/PR
4,12,1499.0,2017-01-01,domingo,00:00:00,GO,153.0,435,ANAPOLIS,Avarias e/ou desgaste excessivo no pneu,Tombamento,Com Vítimas Feridas,Plena Noite,Decrescente,Céu Claro,Dupla,Reta,Sim,8.0,Motocicleta,KASINSKI/COMET 250,2011.0,Condutor,Lesões Graves,24.0,Masculino,0,0,1,0,"-16,27473677","-48,96908998",SR-GO,DEL1/2,UOP01/GO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829722,415073,927619.0,2021-12-13,segunda-feira,06:55:00,SP,116.0,115,TAUBATE,Ultrapassagem Indevida,Colisão transversal,Sem Vítimas,Pleno dia,Crescente,Sol,Dupla,Reta,Não,750642.0,Automóvel,TOYOTA/ETIOS HB XLS,2014.0,Condutor,Ileso,40.0,Feminino,1,0,0,0,-23.049605,-45.599737,SR-SP,UOP02,DEL02
829723,415112,927810.0,2021-11-11,quinta-feira,11:25:00,MG,381.0,385,SAO GONCALO DO RIO ABAIXO,Velocidade Incompatível,Saída de leito carroçável,Com Vítimas Feridas,Pleno dia,Crescente,Ignorado,Simples,Curva,Não,750738.0,Automóvel,FIAT/PALIO FIRE FLEX,2006.0,Passageiro,Lesões Leves,NaN,Feminino,0,1,0,0,-19.828952,-43.355656,SR-MG,UOP01,DEL01
829724,415112,927809.0,2021-11-11,quinta-feira,11:25:00,MG,381.0,385,SAO GONCALO DO RIO ABAIXO,Velocidade Incompatível,Saída de leito carroçável,Com Vítimas Feridas,Pleno dia,Crescente,Ignorado,Simples,Curva,Não,750738.0,Automóvel,FIAT/PALIO FIRE FLEX,2006.0,Condutor,Lesões Leves,NaN,Masculino,0,1,0,0,-19.828952,-43.355656,SR-MG,UOP01,DEL01
829725,415604,929165.0,2021-12-24,sexta-feira,19:30:00,MG,381.0,439,SABARA,Transitar na contramão,Colisão lateral sentido oposto,Com Vítimas Feridas,Plena Noite,Decrescente,Céu Claro,Simples,Curva,Não,751670.0,Automóvel,VW/GOL CL MC,NaN,Condutor,Lesões Leves,67.0,Masculino,0,1,0,0,-19.809277,-43.78706,SR-MG,UOP01,DEL01
829726,415604,929166.0,2021-12-24,sexta-feira,19:30:00,MG,381.0,439,SABARA,Transitar na contramão,Colisão lateral sentido oposto,Com Vítimas Feridas,Plena Noite,Decrescente,Céu Claro,Simples,Curva,Não,751671.0,Automóvel,GM/PRISMA MAXX,NaN,Condutor,Lesões Leves,44.0,Masculino,0,1,0,0,-19.809277,-43.78706,SR-MG,UOP01,DEL01

#### Visão geral Tabela 'Pessoas'
- 829727 linhas
- 35 colunas

In [4]:
df.shape

(829727, 35)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 829727 entries, 0 to 829726
Data columns (total 35 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      829727 non-null  int64
 1   pesid                   829722 non-null  float64
 2   data_inversa            829727 non-null  object
 3   dia_semana              829727 non-null  object
 4   horario                 829727 non-null  object
 5   uf                      829727 non-null  object
 6   br                      828108 non-null  float64
 7   km                      828108 non-null  object
 8   municipio               829727 non-null  object
 9   causa_acidente          829727 non-null  object
 10  tipo_acidente           829727 non-null  object
 11  classificacao_acidente  829727 non-null  object
 12  fase_dia                829727 non-null  object
 13  sentido_via             829727 non-null  object
 14  condicao_metereologica  829727 non-null  object
 15  tipo_pista              829727 non-null  object
 16  tracado_via             829727 non-null  object
 17  uso_solo                829727 non-null  object
 18  id_veiculo              829723 non-null  float64
 19  tipo_veiculo            829727 non-null  object
 20  marca                   787752 non-null  object
 21  ano_fabricacao_veiculo  779844 non-null  float64
 22  tipo_envolvido          829727 non-null  object
 23  estado_fisico           829727 non-null  object
 24  idade                   751306 non-null  float64
 25  sexo                    829727 non-null  object
 26  ilesos                  829727 non-null  int64
 27  feridos_leves           829727 non-null  int64
 28  feridos_graves          829727 non-null  int64
 29  mortos                  829727 non-null  int64
 30  latitude                829727 non-null  object
 31  longitude               829727 non-null  object
 32  regional                829727 non-null  object
 33  delegacia               829727 non-null  object
 34  uop                     801894 non-null  object
dtypes: float64(5), int64(5), object(25)
memory usage: 221.6+ MB

In [7]:
df.describe()

,id,pesid,br,id_veiculo,ano_fabricacao_veiculo,idade,ilesos,feridos_leves,feridos_graves,mortos
count,829727.000000,829722.000000,828108.000000,829723.000000,779844.000000,751306.000000,829727.000000,829727.000000,829727.000000,829727.000000
mean,204403.250686,453549.718753,215.153403,366016.761548,2009.266594,40.510861,0.445823,0.353725,0.108093,0.033169
std,116903.794238,262194.997609,130.893148,211145.818373,7.615540,62.551033,0.497056,0.478125,0.310499,0.179077
min,8.000000,1.000000,10.000000,4.000000,1900.000000,-1.000000,0.000000,0.000000,0.000000,0.000000
25%,102791.500000,224094.250000,101.000000,182932.000000,2006.000000,27.000000,0.000000,0.000000,0.000000,0.000000
50%,204930.000000,455286.500000,163.000000,365437.000000,2011.000000,37.000000,0.000000,0.000000,0.000000,0.000000
75%,305220.000000,679042.750000,343.000000,546457.000000,2014.000000,48.000000,1.000000,1.000000,0.000000,0.000000
max,415604.000000,929166.000000,498.000000,751671.000000,2021.000000,2020.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
df.dtypes

id                          int64
pesid                     float64
data_inversa               object
dia_semana                 object
horario                    object
uf                         object
br                        float64
km                         object
municipio                  object
causa_acidente             object
tipo_acidente              object
classificacao_acidente     object
fase_dia                   object
sentido_via                object
condicao_metereologica     object
tipo_pista                 object
tracado_via                object
uso_solo                   object
id_veiculo                float64
tipo_veiculo               object
marca                      object
ano_fabricacao_veiculo    float64
tipo_envolvido             object
estado_fisico              object
idade                     float64
sexo                       object
ilesos                      int64
feridos_leves               int64
feridos_graves              int64
mortos                      int64
latitude                   object
longitude                  object
regional                   object
delegacia                  object
uop                        object
dtype: object

#### Verifica nulos
- Na tabela Ocorrências 680 nulos em km e br
- pesid 5 nulos

In [9]:
# Removido colunas que decidimos não utilizar na analise
df.drop(['causa_acidente', 'tipo_acidente','classificacao_acidente', 'sentido_via', 'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo','ilesos','feridos_leves', 'feridos_graves', 'mortos','horario','regional', 'delegacia', 'uop'], axis=1, inplace=True)

In [14]:
df[df['id'].isnull()]

Empty DataFrame
Columns: [id, pesid, data_inversa, dia_semana, uf, br, km, municipio, fase_dia, id_veiculo, tipo_veiculo, marca, ano_fabricacao_veiculo, tipo_envolvido, estado_fisico, idade, sexo, latitude, longitude]
Index: []

In [10]:
df[df['pesid'].isnull()]

,id,pesid,data_inversa,dia_semana,uf,br,km,municipio,fase_dia,id_veiculo,tipo_veiculo,marca,ano_fabricacao_veiculo,tipo_envolvido,estado_fisico,idade,sexo,latitude,longitude
188,109,NaN,2017-01-01,domingo,GO,20.0,"220,5",POSSE,Pleno dia,146.0,Semireboque,SR/IBIPORA SR3E FRIG,2008.0,Não Informado,Não Informado,NaN,Não Informado,"-14,14220931","-46,32258922"
204538,100046,NaN,2018-01-01,segunda-feira,TO,153.0,347,GUARAI,Pleno dia,177746.0,Semireboque,REB/KRONE,1996.0,Não Informado,Não Informado,NaN,Não Informado,"-8,952295","-48,500107"
393281,182369,NaN,2019-01-01,terça-feira,PR,277.0,"170,7",PALMEIRA,Pleno dia,325143.0,Motocicleta,I/BMW S1000 RR,2014.0,Não Informado,Não Informado,NaN,Não Informado,"-25,43534","-50,0147"
556281,260357,NaN,2020-01-02,quinta,BA,367.0,"56,6",PORTO SEGURO,Pleno dia,464876.0,AutomÃ³vel,FIAT/UNO MILLE FIRE,2001.0,NÃ£o Informado,NÃ£o Informado,NaN,NÃ£o Informado,"-16,38851188","-39,348101"
704131,331815,NaN,2021-01-01,sexta-feira,CE,222.0,"128,5",ITAPAJE,Pleno dia,596303.0,Automóvel,CITROEN/C3 PICASSO EXC A,2012.0,Não Informado,Não Informado,NaN,Não Informado,-3.707626,-39.623509

In [11]:
df.isna().sum()

id                            0
pesid                         5
data_inversa                  0
dia_semana                    0
uf                            0
br                         1619
km                         1619
municipio                     0
fase_dia                      0
id_veiculo                    4
tipo_veiculo                  0
marca                     41975
ano_fabricacao_veiculo    49883
tipo_envolvido                0
estado_fisico                 0
idade                     78421
sexo                          0
latitude                      0
longitude                     0
dtype: int64

In [12]:
for coluna in df.columns:
    nulo= df[coluna].isna().sum() / df.shape[0]*100
    if(nulo>0):
        print(f"{coluna:{25}}:------> {nulo:.6f}%")

pesid                    :------> 0.000603%
br                       :------> 0.195124%
km                       :------> 0.195124%
id_veiculo               :------> 0.000482%
marca                    :------> 5.058893%
ano_fabricacao_veiculo   :------> 6.011977%
idade                    :------> 9.451422%

##### Remove linhas com pesid nulo

In [13]:
lista=df[df['pesid'].isnull()]
lista=list(lista.id)

In [14]:
df=(df[~df.id.isin(lista)]).reset_index(drop=True)
df.shape

(829708, 19)

##### Remove linhas com id_veiculo nulo

In [15]:
lista=df[df['id_veiculo'].isnull()]
lista=list(lista.id)

In [16]:
df=(df[~df.id.isin(lista)]).reset_index(drop=True)
df.shape

(829704, 19)

##### Dataframe para comparação com ocorrências
Verifica a quantidade de id's unicos nulos

In [17]:
a=df[df['km'].isnull()]

In [18]:
a.groupby('id').count()

,pesid,data_inversa,dia_semana,uf,br,km,municipio,fase_dia,id_veiculo,tipo_veiculo,marca,ano_fabricacao_veiculo,tipo_envolvido,estado_fisico,idade,sexo,latitude,longitude
id,,,,,,,,,,,,,,,,,,
160,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1
472,2,2,2,2,0,0,2,2,2,2,2,2,2,2,2,2,2,2
1506,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1
1721,2,2,2,2,0,0,2,2,2,2,2,2,2,2,2,2,2,2
2465,3,3,3,3,0,0,3,3,3,3,3,1,3,3,2,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403993,2,2,2,2,0,0,2,2,2,2,2,2,2,2,2,2,2,2
404506,5,5,5,5,0,0,5,5,5,5,5,5,5,5,5,5,5,5
404579,2,2,2,2,0,0,2,2,2,2,2,2,2,2,1,2,2,2
407909,3,3,3,3,0,0,3,3,3,3,3,3,3,3,0,3,3,3
411922,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1

In [19]:
#Remove linas com nulos em br e km
df.dropna(subset=['br','km'],inplace=True)

#### Transforma latitude e longitude para float

In [20]:
df['data_inversa']=pd.to_datetime(df['data_inversa'])
df['ano']=pd.DatetimeIndex(df['data_inversa']).year
df.loc[df['ano']<2021, 'latitude'] = df['latitude'].str.replace(',','.')
df.loc[df['ano']<2021, 'longitude'] = df['longitude'].str.replace(',','.')
df=df.drop('ano', axis=1)
df['latitude']=df['latitude'].astype(float)       
df['longitude']=df['longitude'].astype(float)

In [21]:
filtro1=df['latitude']==0
filtro2=df['longitude']==0
df[filtro1&filtro2]

,id,pesid,data_inversa,dia_semana,uf,br,km,municipio,fase_dia,id_veiculo,tipo_veiculo,marca,ano_fabricacao_veiculo,tipo_envolvido,estado_fisico,idade,sexo,latitude,longitude
873,393,591.0,2017-01-02,segunda-feira,RS,386.0,165,CARAZINHO,Pleno dia,499.0,Automóvel,GM/VECTRA GLS,2000.0,Condutor,Ileso,52.0,Masculino,0.0,0.0
874,393,592.0,2017-01-02,segunda-feira,RS,386.0,165,CARAZINHO,Pleno dia,497.0,Caminhonete,FORD/F1000 TURBO XL,1998.0,Condutor,Ileso,59.0,Masculino,0.0,0.0
875,393,590.0,2017-01-02,segunda-feira,RS,386.0,165,CARAZINHO,Pleno dia,500.0,Automóvel,RENAULT/SCENIC RXE 2.0,1999.0,Condutor,Ileso,39.0,Masculino,0.0,0.0
876,393,587.0,2017-01-02,segunda-feira,RS,386.0,165,CARAZINHO,Pleno dia,498.0,Automóvel,FIAT/DOBLO ESSENCE 1.8,2015.0,Condutor,Ileso,34.0,Masculino,0.0,0.0
1275,574,1061.0,2017-01-02,segunda-feira,MG,251.0,418,GRAO MOGOL,Pleno dia,896.0,Automóvel,GM/CELTA 4P LIFE,2006.0,Condutor,Lesões Leves,39.0,Masculino,0.0,0.0
1276,574,1065.0,2017-01-02,segunda-feira,MG,251.0,418,GRAO MOGOL,Pleno dia,896.0,Automóvel,GM/CELTA 4P LIFE,2006.0,Passageiro,Ileso,36.0,Masculino,0.0,0.0
1277,574,1064.0,2017-01-02,segunda-feira,MG,251.0,418,GRAO MOGOL,Pleno dia,896.0,Automóvel,GM/CELTA 4P LIFE,2006.0,Passageiro,Ileso,35.0,Feminino,0.0,0.0
1278,574,1063.0,2017-01-02,segunda-feira,MG,251.0,418,GRAO MOGOL,Pleno dia,896.0,Automóvel,GM/CELTA 4P LIFE,2006.0,Passageiro,Ileso,14.0,Feminino,0.0,0.0
1279,574,1062.0,2017-01-02,segunda-feira,MG,251.0,418,GRAO MOGOL,Pleno dia,896.0,Automóvel,GM/CELTA 4P LIFE,2006.0,Passageiro,Ileso,16.0,Feminino,0.0,0.0
1280,574,2643.0,2017-01-02,segunda-feira,MG,251.0,418,GRAO MOGOL,Pleno dia,910.0,Caminhão-trator,None,NaN,Condutor,Não Informado,NaN,Não Informado,0.0,0.0
2154,995,1636.0,2017-01-04,quarta-feira,RJ,101.0,418,MANGARATIBA,Pleno dia,1394.0,Camioneta,None,NaN,Passageiro,Ileso,69.0,Masculino,0.0,0.0
2155,995,1634.0,2017-01-04,quarta-feira,RJ,101.0,418,MANGARATIBA,Pleno dia,1394.0,Camioneta,None,NaN,Condutor,Ileso,NaN,Masculino,0.0,0.0
2450,1139,2005.0,2017-01-05,quinta-feira,PR,277.0,"36,5",MORRETES,Plena Noite,1685.0,Caminhonete,I/VW AMAROK CD 4X4 HIGH,2012.0,Condutor,Ileso,45.0,Masculino,0.0,0.0
4410,2091,4108.0,2017-01-08,domingo,PR,277.0,"37,5",CURITIBA,Pleno dia,3210.0,Automóvel,RENAULT/LOGAN AUT 1016V,2009.0,Pedestre,Lesões Leves,36.0,Masculino,0.0,0.0
4411,2091,4109.0,2017-01-08,domingo,PR,277.0,"37,5",CURITIBA,Pleno dia,3210.0,Automóvel,RENAULT/LOGAN AUT 1016V,2009.0,Pedestre,Lesões Leves,45.0,Masculino,0.0,0.0
4412,2091,4102.0,2017-01-08,domingo,PR,277.0,"37,5",CURITIBA,Pleno dia,3210.0,Automóvel,RENAULT/LOGAN AUT 1016V,2009.0,Condutor,Ileso,28.0,Masculino,0.0,0.0
4559,2161,6335.0,2017-01-08,domingo,PR,277.0,"35,6",MORRETES,Plena Noite,3372.0,Automóvel,GM/CELTA 3 PORTAS,2002.0,Condutor,Ileso,21.0,Masculino,0.0,0.0
4560,2161,6336.0,2017-01-08,domingo,PR,277.0,"35,6",MORRETES,Plena Noite,3370.0,Automóvel,VW/NOVO FOX HL MD,2016.0,Condutor,Ileso,23.0,Masculino,0.0,0.0
4561,2161,6334.0,2017-01-08,domingo,PR,277.0,"35,6",MORRETES,Plena Noite,3371.0,Automóvel,CHEVROLET/CRUZE LTZ HB,2012.0,Condutor,Ileso,40.0,Masculino,0.0,0.0
5191,2480,4946.0,2017-01-09,segunda-feira,SC,116.0,"134,5",SANTA CECILIA,Pleno dia,3826.0,Automóvel,HYUNDAI/HB20S 1.0M 1.0M,2013.0,Passageiro,Lesões Leves,23.0,Feminino,0.0,0.0
5192,2480,4938.0,2017-01-09,segunda-feira,SC,116.0,"134,5",SANTA CECILIA,Pleno dia,3826.0,Automóvel,HYUNDAI/HB20S 1.0M 1.0M,2013.0,Passageiro,Lesões Leves,28.0,Feminino,0.0,0.0
5193,2480,4935.0,2017-01-09,segunda-feira,SC,116.0,"134,5",SANTA CECILIA,Pleno dia,3826.0,Automóvel,HYUNDAI/HB20S 1.0M 1.0M,2013.0,Condutor,Ileso,40.0,Masculino,0.0,0.0

In [22]:
df=df[~(filtro1 & filtro2)].reset_index(drop=True)

In [23]:
#excluindo linha com localização inconsistente
filtro3=df['id']==146
df[(filtro3)]

,id,pesid,data_inversa,dia_semana,uf,br,km,municipio,fase_dia,id_veiculo,tipo_veiculo,marca,ano_fabricacao_veiculo,tipo_envolvido,estado_fisico,idade,sexo,latitude,longitude
252,146,1550.0,2017-01-01,domingo,BA,101.0,"23,7",RIO REAL,Pleno dia,1273.0,Automóvel,CHEVROLET/ONIX 10MT JOYE,2016.0,Passageiro,Óbito,49.0,Feminino,-50.199409,-94.499996
253,146,1545.0,2017-01-01,domingo,BA,101.0,"23,7",RIO REAL,Pleno dia,1273.0,Automóvel,CHEVROLET/ONIX 10MT JOYE,2016.0,Passageiro,Lesões Graves,42.0,Feminino,-50.199409,-94.499996
254,146,1539.0,2017-01-01,domingo,BA,101.0,"23,7",RIO REAL,Pleno dia,1273.0,Automóvel,CHEVROLET/ONIX 10MT JOYE,2016.0,Condutor,Lesões Leves,40.0,Masculino,-50.199409,-94.499996
255,146,1543.0,2017-01-01,domingo,BA,101.0,"23,7",RIO REAL,Pleno dia,1273.0,Automóvel,CHEVROLET/ONIX 10MT JOYE,2016.0,Passageiro,Lesões Leves,2016.0,Feminino,-50.199409,-94.499996
256,146,1573.0,2017-01-01,domingo,BA,101.0,"23,7",RIO REAL,Pleno dia,1325.0,Caminhão-trator,SCANIA/R 440 A6X4,2013.0,Condutor,Ileso,46.0,Masculino,-50.199409,-94.499996
257,146,1552.0,2017-01-01,domingo,BA,101.0,"23,7",RIO REAL,Pleno dia,1290.0,Caminhão-trator,SCANIA/R 440 A6X2,2012.0,Condutor,Ileso,39.0,Masculino,-50.199409,-94.499996

In [ ]:
# Eliminando as informações comprometidas
df=df[~(filtro3)]

In [27]:
#trocando valores nulos das colunas marca e ano_fabricacao_veiculo por 'Não informado'
df.marca.replace((pd.NA, 'Não informado'), inplace = True)

In [28]:
#preechendo vazios para qeu se sejam possiveis as analises
df.ano_fabricacao_veiculo.replace((pd.NA, 0), inplace = True)

In [30]:
#Corrigindo a coluna Dia Semana
df['dia_semana'].replace(['sexta'],'sexta-feira',inplace=True)
df['dia_semana'].replace(['segunda'],'segunda-feira',inplace=True)
df['dia_semana'].replace(['quinta'],'quinta-feira',inplace=True)
df['dia_semana'].replace(['quarta'],'quarta-feira',inplace=True)
df['dia_semana'].replace(['terça'],'terça-feira',inplace=True)

#### Transformação de 'km' para float

In [31]:
df['km']=df['km'].str.replace(',','.')
df['km']=df['km'].astype(float)

In [32]:
#Corrigindo coluna Sexo
df['sexo'].replace(['Ignorado'],'Não Informado',inplace=True)

In [33]:
#Definindo os tipos de cada coluna
df['id']=df['id'].astype(int)
df['pesid']=df['pesid'].astype(int)
df['ano_fabricacao_veiculo']=df['ano_fabricacao_veiculo'].astype(int)
df['idade']=df['idade'].astype(str)
df['id_veiculo']=df['id_veiculo'].astype(int)
df['dia_semana']=df['dia_semana'].astype(str)
df['uf']=df['uf'].astype(str)
df['km']=df['km'].astype(float)
df['municipio']=df['municipio'].astype(str)
df['tipo_veiculo']=df['tipo_veiculo'].astype(str)
df['estado_fisico']=df['estado_fisico'].astype(str)
df['fase_dia']=df['fase_dia'].astype(str)
df['tipo_envolvido']=df['tipo_envolvido'].astype(str)
df['sexo']=df['sexo'].astype(str)
df['data_inversa'] = pd.to_datetime(df['data_inversa'])

In [34]:
# renomeando para melhor assimilação 
df.rename(columns = {'pesid':'id_pessoa', 'data_inversa':'data', 'br':'rodovia', 'marca':'marca_modelo'}, inplace=True)

#### Exporta dataframe como CSV

In [35]:
df.to_csv('acidentes_pessoas.csv',index=False, encoding='Latin-1')